language: java
jdk: oraclejdk8
install: true

env: DB=pgsql
before_script: psql -c "CREATE DATABASE lastunion;" -U postgres;

script: mvn -q clean integration-test

cache:
  directories: $HOME/.m2

deploy:
  provider: heroku
  api_key: 12345
