language: java
jdk: oraclejdk8
install: true

env: DB=pgsql
before_script: psql -c "CREATE DATABASE lastunion;" -U postgres;

cache:
  directories: $HOME/.m2 
 
deploy: 
  provider: heroku 
  api_key: 12345 
  app: lastunionapp
