language: java
jdk: oraclejdk8
install: true

env: DB=pgsql
before_script: psql -c "CREATE DATABASE lastunion;" -U postgres;

script: mvn -q clean check integration-test

cache:
  directories: $HOME/.m2